[project]
name = "jira-automation"
version = "1.0.0"
description = "Modular Python tool for automating sprint lifecycle tasks in JIRA."
requires-python = ">=3.13"
authors = [{name = "Tyler Baxter", email = "trb7074@gmail.com"}]